/*
Auto generated by c:\Users\snipe_000\source\repos\world_blocks\world_blocks++\shader_lib_gen.py
*/
#include <GL/glew.h>
#include "shaderlib.h"



void CAutoScreenShader::LocateUniforms(){
    this->LocateUniform("textures", this->textures);
    this->LocateUniform("projection", this->projection);
    this->LocateUniform("ssao_kernel", this->ssao_kernel);
}

void CAutoScreenShader::Load(){
    CShader::Load("./shader/screen/screen.vs", "./shader/screen/screen.fs", "./shader/screen/screen.gs");
}

void CAutoBlockShader::LocateUniforms(){
    this->LocateUniform("MVP", this->MVP);
    this->LocateUniform("MV", this->MV);
}

void CAutoBlockShader::Load(){
    CShader::Load("./shader/block/block.vs", "./shader/block/block.fs", "./shader/block/block.gs");
}

// global shader objects
namespace shaderlib {
    AutoScreenShader screen_shader = nullptr;
    AutoBlockShader block_shader = nullptr;
}

void shaderlib::loadshaders(){

    screen_shader = AutoScreenShader(new CAutoScreenShader);
    screen_shader -> Load();
    screen_shader -> LocateUniforms();


    block_shader = AutoBlockShader(new CAutoBlockShader);
    block_shader -> Load();
    block_shader -> LocateUniforms();

}
